version: '3.8'

services:
  
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/usr/src/app
    ports:
      - "80:8000"
    env_file: ./.env.dev
    networks:
      - front
      - db_network
    depends_on:
      - db

  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    networks:
      - db_network
    env_file: ./.env.db


volumes:
  postgres_volume:

networks:
  front:
  db_network:
    internal: true
